<script lang="ts">
import BackHome from "$lib/BackHome.svelte";
import Video from "$lib/Video.svelte";

import bitwig from "./bitwig.avif";
import piano from "./piano.webm";
</script>

<h1>erora</h1>
<p>The musical alias for online user <a href="https://encode42.dev">"encode42".</a> I felt that my online alias didn't sound too great in the context of music, so I decided to split my personalities! I tried to use ChatGPT for name inspiration, yet ended up thinking one up myself. "erora" is a mix of the chill, ambient vibe of an aurora, my tendency to overlook errors, and my experience in programming. Aurora + Error = Errora!</p>
<p>I produce electronic songs designed for background use or solo listening with varying intensities. They're mostly ambient, but with my own, unique style! Typically, I aim to imitate the likes of influential indie video game soundtracks.</p>

<h2>Usage</h2>
<p>I believe in the free, open usage of my creative creations. As such, all of my music is licensed under <a href="https://creativecommons.org/licenses/by/4.0/deed">Creative Commons!</a> As long as you properly credit your source (me), you're free to do whatever you'd like with my music. This includes remixes, covers, inclusion in videos and streams, and usage in a video game.</p>
<p>If you've found my music to be useful in any way, <a href="https://erora.bandcamp.com">please purchase it on Bandcamp!</a> This is the best way to send donations my way, and you always get something in return. You can publicly display it on your profile, get access to lossless audio files to please audiophiles, and support my hobby :)</p>
<p>You may ask, "Can I commission you?" And the answer is: probably not. Only because I struggle to value myself. I wouldn't know what rates to charge, and the increased pressure since money is on the line may impact my resulting work. Instead, <a href="/discord">present your ideas to me directly!</a> If it interests me <a href="/create-estrogen">(which is very easy)</a>, then I'd be more than happy to casually contribute. I'm still trying to build my portfolio before making a career out of this!</p>

<h2>Influences</h2>
<p>Currently, the biggest influences on my works can be sourced from <a href="https://lena.fyi">Lena Raine</a>, <a href="https://c418.org">C418</a>, and <a href="https://www.chrischristodoulou.com">Chris Christodoulou</a>. These three have produced the greatest video game soundtracks of all time! Whether it be Raine's motifs and ambiance, Christodoulou's epic synths and percussion, or C418's simplicity, their styles will always impact me.</p>
<p>I'm also a big fan of Nightmargin's <a href="https://nightmargin.bandcamp.com/album/oneshot-soundtrack">OneShot soundtrack</a>, Mudeth and Ridiculon's work on <a href="https://mudeth.bandcamp.com/album/antibirth-ost">The Binding of Isaac</a>, Toby Fox's <a href="https://tobyfox.bandcamp.com/album/undertale-soundtrack">UNDERTALE</a> and <a href="https://tobyfox.bandcamp.com/album/deltarune-chapter-2-ost">DELTARUNE</a>, and <a href="https://bandcamp.com/encode42">many other similar indie game soundtracks.</a> Various tracks of mine cite these producers as sources of inspiration or motivation.</p>
<p>Bands like <a href="https://porcupinetree.com/recordings/fear-of-a-blank-planet">Porcupine Tree</a>, <a href="https://www.coldplay.com/release/xy">Coldplay</a>, and <a href="https://www.radiohead.com/library#httt">Radiohead</a> have also influenced me in major ways. These are the things I listen to on a daily basis. Though they don't directly overlap with the genres I produce for, they will always affect me in some way. Progressive Rock and adjacent genres are my favorites by far, with bands like <a href="https://riversideband.pl/en/music/albums/wasteland">Riverside</a>, <a href="https://www.airbagsound.com">Airbag</a>, <a href="https://www.opeth.com">Opeth</a>, <a href="https://nosound.band/album/scintilla">Nosound</a>, <a href="https://www.deftones.com/">Deftones</a> populating my playlists. These are all bands I absolutely love! If I start producing progressive rock songs, these will definitely be major inspirations.</p>

<h2>Aspirations</h2>
<p>There's so much I'd love to do in life, especially regarding music! Meeting my idols and talking about various music-related topics is a dream of mine. Literally! Sometimes, I dream about having chats with people learning how they come up with motifs, sound profiles, progression, and more. I look up to so many producers, composers, and songwriters. Speaking with the geniuses that have had such an impact on my own personal style would be absolutely amazing. I could learn so much from a short conversation.</p>
<p>Musicians aren't the only people I'd love to meet! I, as an avid internet user, happen to consume a lot of content. My personality has definitely been impacted by these people, and many have helped me get through the toughest times in my life. It always excites me when I see <a href="https://hermitcraft.com">Hermitcraft content</a> put out, a new video from <a href="https://www.youtube.com/@TheGroop">the members of The Group</a>, more stuff from <a href="https://www.youtube.com/@Aztrosist">Aztrosist</a> is released, or when <a href="https://www.youtube.com/@PosyMusic">Posy drops an amazing video about nothing.</a> There's too many great content creators that I enjoy to list, so instead I featured them <a href="https://www.youtube.com/encode42">on my personal YouTube channel!</a></p>
<p>Lastly, I have a degree in game development. As such, I'd like to develop a game. Over the years, I've put together a list of ideas to use in the future, and I'd like the future to be now. However, I can't do everything alone! When it comes to art, I simply cannot succeed. Coming up with ideas for a storyline is easy, but writing one is not. I can produce the soundtrack, but I'd like some help. These are aspects that I cannot do alone, so I'd like to assemble a team to accomplish my goals. My ideas consist of a rougelike with elements from <a href="https://dead-cells.com">Dead Cells</a> and <a href="https://www.cultofthelamb.com">Cult of the Lamb</a>, a story-driven game that puts the protagonist against the player, and much more. If you're interested, <a href="/discord">talk to me through Discord!</a> I'd love to collaborate to make something great.</p>

<h2>Software</h2>
<p>Currently, my DAW of choice is <a href="https://www.bitwig.com">Bitwig Studio</a>, and I don't see that changing any time soon! I've been more than happy with Bitwig, as it provides every effect I'd need, a great selection of instruments and presets, and nearly unlimited freedom to make whatever I please, all on top of a workflow I excel with. If you're interested in music production, I highly recommend trying it out.</p>
<img src={bitwig} alt="Screenshot of my typical Bitwig layout"/>
<p>Not only that, but it also runs natively on Linux, my daily driver operating system. I initially switched to Linux in 2021 to contribute to software that worked better there. Since then, I stuck with Linux, hopping around various distributions before settling on <a href="https://alexharas.com/post/arch-btw">good 'ol Arch Linux</a>. With open-source or cross-platform plugins such as <a href="https://www.decentsamples.com/product/decent-sampler-plugin">DecentSampler</a>, and the immense power of Bitwig, I believe that audio production on Linux is viable!</p>
<p>Now that I've mentioned DecentSampler, I might as well mention some of the many sample libraries I use. My choice in piano depends on the type of sound I'm going for, but I usually end up using <a href="https://www.pianobook.co.uk/packs/legacy-knight-piano">Legacy Knight</a> or <a href="https://www.pianobook.co.uk/packs/manthey-klaviano">Manthey Klaviano</a>. I'm a big fan of uncommon melodic samples, so I've amassed a large collection of stringed and percussive instruments. This includes <a href="https://www.pianobook.co.uk/packs/pandrum">Pandrum</a>, <a href="https://www.pianobook.co.uk/packs/slinky-violin">Slinky Violin</a>, <a href="https://www.pianobook.co.uk/packs/cymbalon">Cymbalon</a>, and much more. I often find myself browsing for the strangest samples <a href="https://www.pianobook.co.uk/sampler/decent-sampler">on Pianobook!</a> It's a great place to find unique sounds for your songs.</p>
<Video src={piano}/>
<p>I've used a variety of DAWs in the past. GarageBand for iOS is where I produced my first few original tracks. However, I didn't feel content with the result, and blamed it on the DAW. So, without proper research or trying its demo, I purchased a license for FL Studio. For nearly a year, I found it difficult to make music I enjoyed. As it turns out, the DAW is not what makes a song sound good! Luckily, this all changed when I was introduced to Ableton Live through college. Its workflow simply worked with me. I produced multiple tracks I was proud of, and even started dabbling with GarageBand again! I unfortunately couldn't use Ableton after the semester wrapped up, but I looked into other options. Whenever somebody is asking about which DAW to use, I always recommend trying out the demos first. You never know what'll work best for you.</p>

<h2>Myself</h2>
<p>Based in <a href="https://en.wikipedia.org/wiki/Vermont">the green mountains of Vermont</a>, I like to keep things chill! I've been learning music production as a hobby since early 2021. I had dabbled with it since 2016, but never took it seriously. However, with the motivation of one of my college classes, I found my love for music! I'm considering pursuing a degree in music composition, yet I haven't committed, mainly due to financial fears.</p>
<p>My father has been involved in music since my birth year of 2004. Whenever I showed an interest in making my own music, he'd step in and help me out! My first experience producing music was with a pirated copy of Magix Music Maker 2013 that he had burnt onto a DVD. For years, I'd put together pre-made sample loops and claim them as my own. Eventually, I branched out and started to compose patterns from scratch. The constant exposure to his creations has changed my life forever. It may be genetic too, since he was a percussionist, and percussion is where I invest most of my time!</p>
<p>As a middle schooler, I participated in band class. It was there that I learned how to play the saxophone. Though I no longer own it and probably can't play it anymore, this was still an influential period of my musical journey! Seeing my classmates' lack of motivation to improve saddened me, and I strived to set an example. Since then, I've been burdened by the curse of perfectionism.</p>
<p>I'm proud of where I am now. I've learned a lot throughout my journey, but I struggle to figure out how to improve. The lack of critical feedback (despite searching for it), along with my symptoms of imposter syndrome, means that I'm in a negative feedback loop. If you'd like to send me some feedback, <a href="/discord">please join my Discord server!</a> I would love to know what you think of my creations, no matter how positive or negative it may be.</p>

<h2>Website</h2>
<p>This website is over-engineered. I'm a small, unknown hobbyist music producer, yet I've spent hours writing the perfect website. But it's not even perfect! This is due to the fact that my hobbies don't stop at music production. <a href="https://github.com/encode42/flags.sh">I have years of experience in web design and development</a> and have a degree in computer science. As such, not even the simplest of sites can escape my tendency to needlessly overcomplicate tasks! So, in a way, this website is also my web development portfolio.</p>
<p>All content on this website has been automated in some way. For example, new releases have their metadata pulled from Bandcamp and <a href="https://github.com/encode42/erora.live/tree/main/resources">placed in an easily-editable place.</a> I can make changes, select tracks to be featured, and <a href="https://github.com/encode42/erora.live/blob/main/resources/deferred-dreams/tracks/gloom.json#L10">specify where to preview said tracks.</a> Then, I run a command, and everything is processed for me! <a href="https://github.com/encode42/erora.live/blob/main/fetch/build/trim.ts">Track previews are trimmed and filtered,</a> <a href="https://github.com/encode42/erora.live/blob/main/fetch/build/build.ts#L40">cover art is optimized,</a> and unused data gets discarded. I upload the generated code and resources, where they're picked up and built into static webpages. All of this results in a fast website for you to enjoy :)</p>
<p>The code that makes this possible is <a href="https://github.com/encode42/erora.live">open-source on GitHub!</a> Feel free to take what you need from it, <a href="https://github.com/encode42/erora.live/blob/main/license.md">as long as proper credit is provided.</a></p>

<BackHome/>

<style>
	img {
		border-radius: 1rem;
		width: 100%;
	}
</style>
